// Car inventory data
const cars = [
    {
        id: 1,
        make: "Toyota",
        model: "Camry",
        year: 2020,
        price: 24500,
        mileage: 45000,
        fuel: "Hybrid",
        transmission: "Automatic",
        color: "Silver",
        description: "Well-maintained Toyota Camry Hybrid with excellent fuel economy. One owner, full service history.",
        features: ["Leather Seats", "Navigation", "Backup Camera", "Bluetooth", "Cruise Control"]
    },
    {
        id: 2,
        make: "Volkswagen",
        model: "Golf",
        year: 2019,
        price: 18900,
        mileage: 52000,
        fuel: "Diesel",
        transmission: "Manual",
        color: "Blue",
        description: "Sporty VW Golf with efficient diesel engine. Great handling and reliability.",
        features: ["Sport Seats", "Alloy Wheels", "Air Conditioning", "Parking Sensors"]
    },
    {
        id: 3,
        make: "BMW",
        model: "3 Series",
        year: 2021,
        price: 35900,
        mileage: 28000,
        fuel: "Petrol",
        transmission: "Automatic",
        color: "Black",
        description: "Luxury sedan with premium features. Like new condition with low mileage.",
        features: ["Leather Seats", "Sunroof", "Navigation", "Premium Audio", "LED Headlights"]
    },
    {
        id: 4,
        make: "Mercedes-Benz",
        model: "C-Class",
        year: 2018,
        price: 29500,
        mileage: 65000,
        fuel: "Diesel",
        transmission: "Automatic",
        color: "White",
        description: "Elegant Mercedes-Benz C-Class with exceptional comfort and performance.",
        features: ["Leather Interior", "Automatic Climate", "Cruise Control", "Parking Assist"]
    },
    {
        id: 5,
        make: "Audi",
        model: "A4",
        year: 2020,
        price: 32000,
        mileage: 38000,
        fuel: "Petrol",
        transmission: "Automatic",
        color: "Grey",
        description: "Premium Audi A4 with Quattro all-wheel drive. Perfect for Finnish winters.",
        features: ["Quattro AWD", "Virtual Cockpit", "LED Lights", "Heated Seats", "Navigation"]
    },
    {
        id: 6,
        make: "Ford",
        model: "Focus",
        year: 2019,
        price: 15900,
        mileage: 58000,
        fuel: "Petrol",
        transmission: "Manual",
        color: "Red",
        description: "Reliable Ford Focus with great fuel economy. Perfect first car or daily driver.",
        features: ["Air Conditioning", "Bluetooth", "Cruise Control", "Power Windows"]
    },
    {
        id: 7,
        make: "Toyota",
        model: "RAV4",
        year: 2021,
        price: 38500,
        mileage: 22000,
        fuel: "Hybrid",
        transmission: "Automatic",
        color: "Green",
        description: "Spacious hybrid SUV with AWD. Perfect family vehicle with excellent safety ratings.",
        features: ["AWD", "Safety Sense", "Leather Seats", "Panoramic Roof", "7 Seats"]
    },
    {
        id: 8,
        make: "Volkswagen",
        model: "Passat",
        year: 2018,
        price: 19900,
        mileage: 72000,
        fuel: "Diesel",
        transmission: "Automatic",
        color: "Black",
        description: "Executive sedan with plenty of space and comfort. Well-maintained with full service history.",
        features: ["Leather Seats", "Dual Climate", "Navigation", "Parking Sensors", "Xenon Lights"]
    },
    {
        id: 9,
        make: "BMW",
        model: "X3",
        year: 2019,
        price: 42000,
        mileage: 48000,
        fuel: "Diesel",
        transmission: "Automatic",
        color: "White",
        description: "Premium SUV with xDrive all-wheel drive. Luxury and practicality combined.",
        features: ["xDrive AWD", "Panoramic Roof", "Harman Kardon Audio", "Heated Seats", "Power Tailgate"]
    },
    {
        id: 10,
        make: "Audi",
        model: "Q5",
        year: 2020,
        price: 45500,
        mileage: 32000,
        fuel: "Diesel",
        transmission: "Automatic",
        color: "Grey",
        description: "Sophisticated SUV with cutting-edge technology and supreme comfort.",
        features: ["Quattro AWD", "Virtual Cockpit", "Matrix LED", "Air Suspension", "Bang & Olufsen"]
    },
    {
        id: 11,
        make: "Mercedes-Benz",
        model: "E-Class",
        year: 2019,
        price: 38900,
        mileage: 55000,
        fuel: "Diesel",
        transmission: "Automatic",
        color: "Silver",
        description: "Executive sedan with unmatched luxury and advanced safety features.",
        features: ["Leather Interior", "Burmester Audio", "360 Camera", "Massage Seats", "Night Package"]
    },
    {
        id: 12,
        make: "Ford",
        model: "Fiesta",
        year: 2020,
        price: 13900,
        mileage: 35000,
        fuel: "Petrol",
        transmission: "Manual",
        color: "Blue",
        description: "Compact and economical city car. Perfect for urban driving with low running costs.",
        features: ["Air Conditioning", "Bluetooth", "USB Port", "Electric Windows", "Remote Central Locking"]
    }
];
